### ISSUE TITLE
Dont work with domains, that contains underscore (_)

### ISSUE THREAD

**Issue by sv-atoslav** [vijayhardaha/webscreenshot.now.sh#3]
# Manual screenshot of https://anastasia_admin.mymadcrmdemo.com/ 
![image](https://user-images.githubusercontent.com/28783346/115708575-da5f1700-a378-11eb-9ba8-7d5e0f43310a.png)
# Your [site with tool](https://webscreenshot.vercel.app/) reaction : 
![image](https://user-images.githubusercontent.com/28783346/115708773-13978700-a379-11eb-8e70-87d24184b2a3.png)
Please, add support of special characters.

**Comment by vijayhardaha** [comment]
Underscore characters are not permitted in domain names in accordance with RFC 1035.
[Click here for more information here](https://blog.entrust.com/2019/01/removal-of-underscores-from-domain-names/)
