### ISSUE TITLE
Demo doesnt work?

### ISSUE THREAD

**Issue by BhawaniGarg** [vijayhardaha/webscreenshot.now.sh#5]
I tried with a tweet link bt it gives error :(

**Comment by vijayhardaha** [comment]
I guess, There are some changes in the [Twitter publisher](https://publish.twitter.com/) website. Maybe due to animation, the element height is coming 0.

I will check what is the issue there.

**Comment by vijayhardaha** [comment]
Should be ok now. It fails on many websites that have too many ads or loading time is too high.
I am still looking for the best settings to reduce the load time.

**Comment by BhawaniGarg** [comment]
Thank you for the super fast response.
